name: schedule-actions
on: 
  schedule:
    - cron: 0 3,11,19 * * *
jobs:
  build-job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: scripts/install
      - run: git config --global user.name github-actions
      - run: git config --global user.email github-actions@github.com
      - run: npm run schedule-action
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          DKR_USER: ${{ secrets.DKR_USER }}
          DKR_PWD: ${{ secrets.DKR_PWD }}
